# Generated by Django 3.0.6 on 2020-08-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0003_userdiary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDiary',
            new_name='Diaries',
        ),
    ]
