# Generated by Django 3.0.6 on 2020-08-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0004_auto_20200827_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diaries',
        ),
    ]
