# Generated by Django 3.0.6 on 2020-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0005_delete_diaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primkey', models.IntegerField()),
                ('article', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
