# Generated by Django 3.0.6 on 2020-08-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0009_user_logindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userimg',
            field=models.ImageField(default='no-image.png', upload_to='personimage/'),
        ),
    ]
