# Generated by Django 3.0.6 on 2020-08-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0011_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
