# Generated by Django 3.0.6 on 2020-08-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0012_delete_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('primkey', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('sended', models.DateTimeField(auto_now_add=True)),
                ('opend', models.BooleanField(default=False)),
                ('sendisme', models.BooleanField(default=True)),
                ('message', models.CharField(default='', max_length=1000)),
                ('friendid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IfBoxHp.User')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to='IfBoxHp.User')),
            ],
        ),
    ]
