# Generated by Django 3.0.6 on 2020-09-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0013_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='primkey',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
    ]
