# Generated by Django 3.0.6 on 2020-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0014_auto_20200904_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='primkey',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
