# Generated by Django 3.0.6 on 2020-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0015_auto_20200904_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('primkey', models.AutoField(primary_key=True, serialize=False)),
                ('adminid', models.CharField(default='', max_length=1000)),
                ('adminpass1', models.CharField(default='', max_length=1000)),
                ('aduminpass2', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
