# Generated by Django 3.0.6 on 2020-09-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0018_auto_20200924_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admininformation',
            old_name='aduminpass2',
            new_name='adminpass2',
        ),
    ]
