# Generated by Django 3.0.6 on 2020-09-25 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0020_auto_20200924_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('primkey', models.AutoField(primary_key=True, serialize=False)),
                ('compname', models.CharField(max_length=1000)),
                ('nowrunning', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('primkey', models.AutoField(primary_key=True, serialize=False)),
                ('employeename', models.CharField(max_length=1000)),
                ('jobstatus', models.BooleanField(default=False)),
                ('loginid', models.CharField(max_length=100)),
                ('loginidpass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenbaInfo',
            fields=[
                ('primkey', models.AutoField(primary_key=True, serialize=False)),
                ('genbaname', models.CharField(max_length=1000)),
                ('nowrunning', models.BooleanField(default=True)),
                ('compofgenba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IfBoxHp.CustomerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='RunningInfo',
            fields=[
                ('primkey', models.AutoField(primary_key=True, serialize=False)),
                ('attendancetime', models.DateTimeField()),
                ('leavetime', models.DateTimeField()),
                ('employeeofrun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IfBoxHp.EmployeeInfo')),
                ('genbainfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IfBoxHp.GenbaInfo')),
            ],
        ),
    ]
