# Generated by Django 3.0.6 on 2020-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0021_customerinfo_employeeinfo_genbainfo_runninginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='lastgenba',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='runninginfo',
            name='attendancetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='runninginfo',
            name='leavetime',
            field=models.DateTimeField(null=True),
        ),
    ]
