# Generated by Django 3.0.6 on 2020-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0022_auto_20200926_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='genbainfo',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='genbainfo',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
