# Generated by Django 3.0.6 on 2020-09-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0023_auto_20200927_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='runninginfo',
            name='zangyotime',
            field=models.FloatField(null=True),
        ),
    ]
