# Generated by Django 3.0.6 on 2020-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IfBoxHp', '0026_employeeinfo_loginaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininformation',
            name='uselogin',
            field=models.BooleanField(default=True),
        ),
    ]
